CREATE TABLE IF NOT EXISTS HOTEL(
HOTEL_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
HOTEL_NAME TEXT NOT NULL,
HOTEL_ADDRESS TEXT NOT NULL,
CITY TEXT NOT NULL,
POSTCODE TEXT NOT NULL,
HOTEL_TELNO TEXT NOT NULL UNIQUE,
HOTEL_EMAIL TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USER(
USER_ID INTEGER  NOT NULL  PRIMARY KEY AUTOINCREMENT,
USERNAME TEXT NOT NULL UNIQUE,
USER_PASSWORD TEXT NOT NULL,
ROLE TEXT NOT NULL,
F_NAME TEXT NOT NULL,
M_NAME TEXT,
L_NAME TEXT NOT NULL,
USER_EMAIL TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ROOM_TYPE(
ROOM_TYPE_ID INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
ROOM_TYPE_NAME TEXT NOT NULL,
ROOM_TYPE_DESCRIPTION TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ROOM(
ROOM_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
ROOM_NO INTEGER NOT NULL,
ROOM_TYPE_ID INTEGER NOT NULL,
PRICE DOUBLE(2) NOT NULL,
HOTEL_ID INTEGER NOT NULL,
FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPE(ROOM_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(HOTEL_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS GUEST(
GUEST_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
F_NAME TEXT NOT NULL,
M_NAME TEXT,
L_NAME TEXT NOT NULL,
GUEST_ADDRESS TEXT NOT NULL,
CITY TEXT NOT NULL,
POSTCODE TEXT NOT NULL,
GUEST_EMAIL TEXT NOT NULL UNIQUE,
GUEST_PHNO TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS BOOKING(
BOOKING_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
NO_OF_GUEST INTEGER NOT NULL,
DATE_IN DATE NOT NULL,
DATE_OUT DATE NOT NULL,
TIMESTAMP DATETIME NOT NULL NOT NULL DEFAULT (CURRENT_TIMESTAMP),
GUEST_ID INTEGER NOT NULL,
ROOM_ID INTEGER NOT NULL,
FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID) ON DELETE CASCADE ON UPDATE CASCADE
FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PAYMENT_TYPE(
TYPE INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
DESCRIPTION TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PAYMENT(
PAYMENT_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
AMOUNT DOUBLE(2) NOT NULL,
TYPE INTEGER NOT NULL,
TIMESTAMP DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP),
STATUS BOOLEAN NOT NULL CHECK (STATUS IN (0 , 1)),
BOOKING_ID INTEGER NOT NULL UNIQUE,
FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (TYPE) REFERENCES PAYMENT_TYPE(TYPE) ON DELETE CASCADE ON UPDATE CASCADE
);


